/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'UTC' | 'Europe/Istanbul';

export interface Config {
  auth: {
    users: UserAuthOperations;
    members: MemberAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    cities: City;
    countries: Country;
    days: Day;
    genders: Gender;
    roles: Role;
    members: Member;
    'member-accounts': MemberAccount;
    conversations: Conversation;
    messages: Message;
    memory: Memory;
    folders: Folder;
    usage: Usage;
    'login-sessions': LoginSession;
    'member-login-sessions': MemberLoginSession;
    permissions: Permission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    members: {
      accounts: 'member-accounts';
      conversations: 'conversations';
      memory: 'memory';
      folders: 'folders';
    };
    conversations: {
      messages: 'messages';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    days: DaysSelect<false> | DaysSelect<true>;
    genders: GendersSelect<false> | GendersSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'member-accounts': MemberAccountsSelect<false> | MemberAccountsSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    memory: MemorySelect<false> | MemorySelect<true>;
    folders: FoldersSelect<false> | FoldersSelect<true>;
    usage: UsageSelect<false> | UsageSelect<true>;
    'login-sessions': LoginSessionsSelect<false> | LoginSessionsSelect<true>;
    'member-login-sessions': MemberLoginSessionsSelect<false> | MemberLoginSessionsSelect<true>;
    permissions: PermissionsSelect<false> | PermissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'tr' | 'tr'[];
  globals: {
    theme: Theme;
    integrations: Integration;
    cookiePolicy: CookiePolicy;
    persona: Persona;
    prompts: Prompt;
    llm: Llm;
    embedding: Embedding;
    retrieval: Retrieval;
    memorySettings: MemorySetting;
    limits: Limit;
  };
  globalsSelect: {
    theme: ThemeSelect<false> | ThemeSelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
    cookiePolicy: CookiePolicySelect<false> | CookiePolicySelect<true>;
    persona: PersonaSelect<false> | PersonaSelect<true>;
    prompts: PromptsSelect<false> | PromptsSelect<true>;
    llm: LlmSelect<false> | LlmSelect<true>;
    embedding: EmbeddingSelect<false> | EmbeddingSelect<true>;
    retrieval: RetrievalSelect<false> | RetrievalSelect<true>;
    memorySettings: MemorySettingsSelect<false> | MemorySettingsSelect<true>;
    limits: LimitsSelect<false> | LimitsSelect<true>;
  };
  locale: 'tr';
  widgets: {
    'banner-widget': BannerWidgetWidget;
    collections: CollectionsWidget;
  };
  strictDraftTypes: true;
  user: User | Member;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface MemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Yönetim paneli (admin) kullanıcıları. Asistan üyelerinden (Members) tamamen ayrıdır.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  password?: string | null;
  /**
   * Kullanıcının rollerini seçin.
   */
  roles: string | Role;
  /**
   * Kullanıcının ilk adını girin.
   */
  firstName: string;
  /**
   * Kullanıcının soyadını girin.
   */
  lastName: string;
  /**
   * Kullanıcının doğum tarihini girin.
   */
  birthDate?: string | null;
  /**
   * Kullanıcının cinsiyetini seçin.
   */
  gender: string | Gender;
  /**
   * Kullanıcının ülkesini seçin.
   */
  country?: (string | null) | Country;
  /**
   * Kullanıcının şehrini seçin.
   */
  city?: (string | null) | City;
  /**
   * Kullanıcının ilçesini girin.
   */
  district?: string | null;
  /**
   * Kullanıcının tam adresini girin.
   */
  address?: string | null;
  /**
   * Kullanıcının sabit telefon numarasını girin.
   */
  landline?: string | null;
  /**
   * Kullanıcının cep telefon numarasını girin.
   */
  gsm?: string | null;
  images?: {
    /**
     * 16x9 görseli (1920x1080)
     */
    ratio16x9?: (string | null) | Media;
    /**
     * 9x16 görseli (1080x1920)
     */
    ratio9x16?: (string | null) | Media;
    /**
     * 1x1 görseli (1080x1080)
     */
    ratio1x1?: (string | null) | Media;
  };
  /**
   * Bu içeriği oluşturan kullanıcı
   */
  createdBy?: (string | null) | User;
  /**
   * Bu içeriği güncelleyen son kullanıcı
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  collection: 'users';
}
/**
 * Sistem rolleri (admin = süper yetkili). Kullanıcılara atanır; ince yetkiler İzinler koleksiyonunda.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: string;
  /**
   * Sayfa başlığı (Rol adı)
   */
  title: string;
  /**
   * Sayfa açıklaması (Rol açıklaması)
   */
  description: string;
  /**
   * Bilgilendirme amaçlı etiket. Gerçek yetkilendirme "Permissions" koleksiyonundaki kullanıcı kayıtları üzerinden uygulanır.
   */
  permissions: ('create' | 'read' | 'update' | 'delete')[];
  /**
   * Sayfa URL'sinde kullanılacak benzersiz tanımlayıcı
   */
  slug: string;
  /**
   * Bu içeriği oluşturan kullanıcı
   */
  createdBy?: (string | null) | User;
  /**
   * Bu içeriği güncelleyen son kullanıcı
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Cinsiyet tanımları. Üye/kullanıcı profillerinde kullanılan referans verisi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genders".
 */
export interface Gender {
  id: string;
  /**
   * Cinsiyet adı (dile göre — örn. Erkek / Male)
   */
  title: string;
  /**
   * Opsiyonel açıklama
   */
  description?: string | null;
  /**
   * Sayfa URL'sinde kullanılacak benzersiz tanımlayıcı
   */
  slug: string;
  /**
   * Bu içeriği oluşturan kullanıcı
   */
  createdBy?: (string | null) | User;
  /**
   * Bu içeriği güncelleyen son kullanıcı
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Ülke tanımları (ISO kodu, telefon kodu). Şehirlerin bağlı olduğu referans verisi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: string;
  /**
   * Ülke adı (dile göre — örn. Türkiye / Turkey)
   */
  title: string;
  /**
   * 2 harfli ISO 3166-1 ülke kodu (büyük harf)
   */
  iso2: string;
  /**
   * Uluslararası arama kodu (opsiyonel)
   */
  dialCode?: string | null;
  /**
   * Opsiyonel açıklama
   */
  description?: string | null;
  /**
   * Sayfa URL'sinde kullanılacak benzersiz tanımlayıcı
   */
  slug: string;
  /**
   * Bu içeriği oluşturan kullanıcı
   */
  createdBy?: (string | null) | User;
  /**
   * Bu içeriği güncelleyen son kullanıcı
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Şehir/il tanımları. Ülkeye bağlı referans verisi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: string;
  /**
   * Şehir adı (dile göre — örn. İstanbul / Istanbul)
   */
  title: string;
  /**
   * Şehrin bağlı olduğu ülke
   */
  country: string | Country;
  /**
   * İl plaka kodu (opsiyonel — TR için)
   */
  plateCode?: string | null;
  /**
   * Opsiyonel açıklama
   */
  description?: string | null;
  /**
   * Sayfa URL'sinde kullanılacak benzersiz tanımlayıcı
   */
  slug: string;
  /**
   * Bu içeriği oluşturan kullanıcı
   */
  createdBy?: (string | null) | User;
  /**
   * Bu içeriği güncelleyen son kullanıcı
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Yüklenen görsel ve dosyalar. Okuma herkese açık; yazma yetkiye bağlı.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Görselin erişilebilirlik açıklaması (alt text)
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Haftanın günleri / gün tanımları (sıralı referans verisi).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "days".
 */
export interface Day {
  id: string;
  /**
   * Gün adı (dile göre — örn. Pazartesi / Monday)
   */
  title: string;
  /**
   * Haftanın günü sırası: 0 = Pazartesi … 6 = Pazar (dil-bağımsız sıralama)
   */
  dayIndex: number;
  /**
   * Opsiyonel açıklama
   */
  description?: string | null;
  /**
   * Sayfa URL'sinde kullanılacak benzersiz tanımlayıcı
   */
  slug: string;
  /**
   * Bu içeriği oluşturan kullanıcı
   */
  createdBy?: (string | null) | User;
  /**
   * Bu içeriği güncelleyen son kullanıcı
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Asistan son kullanıcıları (üyeler). Admin kullanıcılarından tamamen ayrı; kendi giriş sistemiyle kayıt olur. Bağlı giriş yöntemleri "Üye Hesapları"nda tutulur.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: string;
  password?: string | null;
  /**
   * Engelli üye giriş yapamaz (yalnız yönetici değiştirir).
   */
  status: 'active' | 'blocked';
  /**
   * Üyenin tercih ettiği dil (örn. tr).
   */
  locale?: string | null;
  lastSeenAt?: string | null;
  /**
   * Üyenin adı.
   */
  firstName?: string | null;
  /**
   * Üyenin soyadı.
   */
  lastName?: string | null;
  /**
   * Üyenin doğum tarihi (opsiyonel).
   */
  birthDate?: string | null;
  /**
   * Üyenin cinsiyeti (opsiyonel).
   */
  gender?: (string | null) | Gender;
  /**
   * Üyenin ülkesi.
   */
  country?: (string | null) | Country;
  /**
   * Üyenin şehri.
   */
  city?: (string | null) | City;
  /**
   * Üyenin ilçesi.
   */
  district?: string | null;
  /**
   * Üyenin açık adresi.
   */
  address?: string | null;
  /**
   * Üyenin cep telefonu.
   */
  gsm?: string | null;
  /**
   * Üyenin sabit telefonu.
   */
  landline?: string | null;
  /**
   * Üyenin profil görseli (opsiyonel).
   */
  avatar?: (string | null) | Media;
  accounts?: {
    docs?: (string | MemberAccount)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  conversations?: {
    docs?: (string | Conversation)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  memory?: {
    docs?: (string | Memory)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folders?: {
    docs?: (string | Folder)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  collection: 'members';
}
/**
 * Bir üyenin bağlı giriş yöntemleri (Google, Apple, ...). Üye birden çok yöntemle giriş yapabilir. Salt okunur — OAuth akışı sunucu tarafında yazar; üye kendi bağlı hesabını kaldırabilir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-accounts".
 */
export interface MemberAccount {
  id: string;
  member: string | Member;
  provider: 'google' | 'apple';
  /**
   * Sağlayıcının verdiği benzersiz kullanıcı kimliği (OAuth "sub").
   */
  providerAccountId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Üyelerin asistan sohbetleri. Salt okunur — sunucu tarafında oluşturulur; mesaj/token sayacı ve özet içerir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: string;
  member?: (string | null) | Member;
  folder?: (string | null) | Folder;
  title?: string | null;
  /**
   * Konuşma özeti — her tur sonunda güncellenir.
   */
  summary?: string | null;
  status?: ('active' | 'archived') | null;
  messageCount?: number | null;
  tokensTotal?: number | null;
  lastMessageAt?: string | null;
  /**
   * Bu konuşmaya ait mesajlar (kronolojik).
   */
  messages?: {
    docs?: (string | Message)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Üyelerin sohbetlerini grupladığı klasörler. Salt okunur — üye tarafında oluşturulur.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders".
 */
export interface Folder {
  id: string;
  member: string | Member;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sohbetlerdeki tekil mesajlar (kullanıcı/asistan). Salt okunur — sunucu tarafında yazılır; üye yalnızca kendi mesajının geri bildirimini (👍/👎) güncelleyebilir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  conversation: string | Conversation;
  member?: (string | null) | Member;
  role: 'user' | 'assistant';
  content: string;
  /**
   * Kullanılan kaynaklar [{n,title,url,score}]
   */
  citations?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  tokensIn?: number | null;
  tokensOut?: number | null;
  feedback?: ('up' | 'down') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Üye hakkında konuşmalar arası hatırlanan kalıcı bilgiler (Katman 4). Salt okunur — sunucu tarafında çıkarılır.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memory".
 */
export interface Memory {
  id: string;
  member: string | Member;
  /**
   * Kullanıcı hakkında kalıcı gerçek (örn. tercih, durum)
   */
  text: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Günlük asistan kullanım sayacı (mesaj + token). Salt okunur — sunucu tarafında yazılır.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage".
 */
export interface Usage {
  id: string;
  day: string;
  messageCount?: number | null;
  tokenCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Yönetim paneli (admin) kullanıcılarının her başarılı girişinde kaydedilen oturum bilgisi. Salt okunur, yalnız yöneticiler görür.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-sessions".
 */
export interface LoginSession {
  id: string;
  /**
   * Giriş yapan admin kullanıcısı.
   */
  user: string | User;
  status: 'success' | 'failed';
  ipAddress?: string | null;
  deviceType?: ('desktop' | 'mobile' | 'tablet' | 'bot' | 'unknown') | null;
  browser?: string | null;
  os?: string | null;
  /**
   * İstemcinin gönderdiği ham User-Agent başlığı.
   */
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Üyelerin her başarılı girişinde kaydedilen oturum bilgisi. Salt okunur; üye yalnız kendi kayıtlarını görür, yönetici tümünü görür.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-login-sessions".
 */
export interface MemberLoginSession {
  id: string;
  /**
   * Giriş yapan üye.
   */
  member: string | Member;
  status: 'success' | 'failed';
  ipAddress?: string | null;
  deviceType?: ('desktop' | 'mobile' | 'tablet' | 'bot' | 'unknown') | null;
  browser?: string | null;
  os?: string | null;
  /**
   * İstemcinin gönderdiği ham User-Agent başlığı.
   */
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kullanıcı yetkilerini yönetin - Her kullanıcı için tek kayıt
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions".
 */
export interface Permission {
  id: string;
  /**
   * Yetkilerin atanacağı kullanıcı
   */
  user: string | User;
  /**
   * Tüm yetkileri geçici olarak devre dışı bırakabilirsiniz
   */
  isActive?: boolean | null;
  users: {
    scope: 'none' | 'own' | 'all';
    actions?: ('create' | 'read' | 'update' | 'delete' | 'publish' | 'hardDelete' | 'readVersions')[] | null;
  };
  media: {
    scope: 'none' | 'own' | 'all';
    actions?: ('create' | 'read' | 'update' | 'delete' | 'publish' | 'hardDelete' | 'readVersions')[] | null;
  };
  cities: {
    scope: 'none' | 'own' | 'all';
    actions?: ('create' | 'read' | 'update' | 'delete' | 'publish' | 'hardDelete' | 'readVersions')[] | null;
  };
  countries: {
    scope: 'none' | 'own' | 'all';
    actions?: ('create' | 'read' | 'update' | 'delete' | 'publish' | 'hardDelete' | 'readVersions')[] | null;
  };
  days: {
    scope: 'none' | 'own' | 'all';
    actions?: ('create' | 'read' | 'update' | 'delete' | 'publish' | 'hardDelete' | 'readVersions')[] | null;
  };
  genders: {
    scope: 'none' | 'own' | 'all';
    actions?: ('create' | 'read' | 'update' | 'delete' | 'publish' | 'hardDelete' | 'readVersions')[] | null;
  };
  roles: {
    scope: 'none' | 'own' | 'all';
    actions?: ('create' | 'read' | 'update' | 'delete' | 'publish' | 'hardDelete' | 'readVersions')[] | null;
  };
  members: {
    scope: 'none' | 'own' | 'all';
    actions?: ('create' | 'read' | 'update' | 'delete' | 'publish' | 'hardDelete' | 'readVersions')[] | null;
  };
  'member-accounts': {
    scope: 'none' | 'own' | 'all';
    actions?: ('create' | 'read' | 'update' | 'delete' | 'publish' | 'hardDelete' | 'readVersions')[] | null;
  };
  conversations: {
    scope: 'none' | 'own' | 'all';
    actions?: ('create' | 'read' | 'update' | 'delete' | 'publish' | 'hardDelete' | 'readVersions')[] | null;
  };
  messages: {
    scope: 'none' | 'own' | 'all';
    actions?: ('create' | 'read' | 'update' | 'delete' | 'publish' | 'hardDelete' | 'readVersions')[] | null;
  };
  memory: {
    scope: 'none' | 'own' | 'all';
    actions?: ('create' | 'read' | 'update' | 'delete' | 'publish' | 'hardDelete' | 'readVersions')[] | null;
  };
  folders: {
    scope: 'none' | 'own' | 'all';
    actions?: ('create' | 'read' | 'update' | 'delete' | 'publish' | 'hardDelete' | 'readVersions')[] | null;
  };
  usage: {
    scope: 'none' | 'own' | 'all';
    actions?: ('create' | 'read' | 'update' | 'delete' | 'publish' | 'hardDelete' | 'readVersions')[] | null;
  };
  'login-sessions': {
    scope: 'none' | 'own' | 'all';
    actions?: ('create' | 'read' | 'update' | 'delete' | 'publish' | 'hardDelete' | 'readVersions')[] | null;
  };
  'member-login-sessions': {
    scope: 'none' | 'own' | 'all';
    actions?: ('create' | 'read' | 'update' | 'delete' | 'publish' | 'hardDelete' | 'readVersions')[] | null;
  };
  theme: {
    /**
     * Kullanıcının yapabileceği işlemler
     */
    actions: ('none' | 'read' | 'update' | 'readVersions')[];
  };
  integrations: {
    /**
     * Kullanıcının yapabileceği işlemler
     */
    actions: ('none' | 'read' | 'update' | 'readVersions')[];
  };
  cookiePolicy: {
    /**
     * Kullanıcının yapabileceği işlemler
     */
    actions: ('none' | 'read' | 'update' | 'readVersions')[];
  };
  persona: {
    /**
     * Kullanıcının yapabileceği işlemler
     */
    actions: ('none' | 'read' | 'update' | 'readVersions')[];
  };
  prompts: {
    /**
     * Kullanıcının yapabileceği işlemler
     */
    actions: ('none' | 'read' | 'update' | 'readVersions')[];
  };
  llm: {
    /**
     * Kullanıcının yapabileceği işlemler
     */
    actions: ('none' | 'read' | 'update' | 'readVersions')[];
  };
  embedding: {
    /**
     * Kullanıcının yapabileceği işlemler
     */
    actions: ('none' | 'read' | 'update' | 'readVersions')[];
  };
  retrieval: {
    /**
     * Kullanıcının yapabileceği işlemler
     */
    actions: ('none' | 'read' | 'update' | 'readVersions')[];
  };
  memorySettings: {
    /**
     * Kullanıcının yapabileceği işlemler
     */
    actions: ('none' | 'read' | 'update' | 'readVersions')[];
  };
  limits: {
    /**
     * Kullanıcının yapabileceği işlemler
     */
    actions: ('none' | 'read' | 'update' | 'readVersions')[];
  };
  /**
   * Kullanıcının dashboard'da görebileceği widget'lar. Seçilmezse hiçbir widget görünmez. Admin kullanıcılar her zaman tüm widget'ları görür.
   */
  widgets?: 'banner-widget'[] | null;
  /**
   * Bu içeriği oluşturan kullanıcı
   */
  createdBy?: (string | null) | User;
  /**
   * Bu içeriği güncelleyen son kullanıcı
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'cities';
        value: string | City;
      } | null)
    | ({
        relationTo: 'countries';
        value: string | Country;
      } | null)
    | ({
        relationTo: 'days';
        value: string | Day;
      } | null)
    | ({
        relationTo: 'genders';
        value: string | Gender;
      } | null)
    | ({
        relationTo: 'roles';
        value: string | Role;
      } | null)
    | ({
        relationTo: 'members';
        value: string | Member;
      } | null)
    | ({
        relationTo: 'member-accounts';
        value: string | MemberAccount;
      } | null)
    | ({
        relationTo: 'conversations';
        value: string | Conversation;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'memory';
        value: string | Memory;
      } | null)
    | ({
        relationTo: 'folders';
        value: string | Folder;
      } | null)
    | ({
        relationTo: 'usage';
        value: string | Usage;
      } | null)
    | ({
        relationTo: 'login-sessions';
        value: string | LoginSession;
      } | null)
    | ({
        relationTo: 'member-login-sessions';
        value: string | MemberLoginSession;
      } | null)
    | ({
        relationTo: 'permissions';
        value: string | Permission;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'members';
        value: string | Member;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'members';
        value: string | Member;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  password?: T;
  roles?: T;
  firstName?: T;
  lastName?: T;
  birthDate?: T;
  gender?: T;
  country?: T;
  city?: T;
  district?: T;
  address?: T;
  landline?: T;
  gsm?: T;
  images?:
    | T
    | {
        ratio16x9?: T;
        ratio9x16?: T;
        ratio1x1?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  title?: T;
  country?: T;
  plateCode?: T;
  description?: T;
  slug?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  title?: T;
  iso2?: T;
  dialCode?: T;
  description?: T;
  slug?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "days_select".
 */
export interface DaysSelect<T extends boolean = true> {
  title?: T;
  dayIndex?: T;
  description?: T;
  slug?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genders_select".
 */
export interface GendersSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slug?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  permissions?: T;
  slug?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  password?: T;
  status?: T;
  locale?: T;
  lastSeenAt?: T;
  firstName?: T;
  lastName?: T;
  birthDate?: T;
  gender?: T;
  country?: T;
  city?: T;
  district?: T;
  address?: T;
  gsm?: T;
  landline?: T;
  avatar?: T;
  accounts?: T;
  conversations?: T;
  memory?: T;
  folders?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-accounts_select".
 */
export interface MemberAccountsSelect<T extends boolean = true> {
  member?: T;
  provider?: T;
  providerAccountId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  member?: T;
  folder?: T;
  title?: T;
  summary?: T;
  status?: T;
  messageCount?: T;
  tokensTotal?: T;
  lastMessageAt?: T;
  messages?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  conversation?: T;
  member?: T;
  role?: T;
  content?: T;
  citations?: T;
  tokensIn?: T;
  tokensOut?: T;
  feedback?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memory_select".
 */
export interface MemorySelect<T extends boolean = true> {
  member?: T;
  text?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders_select".
 */
export interface FoldersSelect<T extends boolean = true> {
  member?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage_select".
 */
export interface UsageSelect<T extends boolean = true> {
  day?: T;
  messageCount?: T;
  tokenCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-sessions_select".
 */
export interface LoginSessionsSelect<T extends boolean = true> {
  user?: T;
  status?: T;
  ipAddress?: T;
  deviceType?: T;
  browser?: T;
  os?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-login-sessions_select".
 */
export interface MemberLoginSessionsSelect<T extends boolean = true> {
  member?: T;
  status?: T;
  ipAddress?: T;
  deviceType?: T;
  browser?: T;
  os?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions_select".
 */
export interface PermissionsSelect<T extends boolean = true> {
  user?: T;
  isActive?: T;
  users?:
    | T
    | {
        scope?: T;
        actions?: T;
      };
  media?:
    | T
    | {
        scope?: T;
        actions?: T;
      };
  cities?:
    | T
    | {
        scope?: T;
        actions?: T;
      };
  countries?:
    | T
    | {
        scope?: T;
        actions?: T;
      };
  days?:
    | T
    | {
        scope?: T;
        actions?: T;
      };
  genders?:
    | T
    | {
        scope?: T;
        actions?: T;
      };
  roles?:
    | T
    | {
        scope?: T;
        actions?: T;
      };
  members?:
    | T
    | {
        scope?: T;
        actions?: T;
      };
  'member-accounts'?:
    | T
    | {
        scope?: T;
        actions?: T;
      };
  conversations?:
    | T
    | {
        scope?: T;
        actions?: T;
      };
  messages?:
    | T
    | {
        scope?: T;
        actions?: T;
      };
  memory?:
    | T
    | {
        scope?: T;
        actions?: T;
      };
  folders?:
    | T
    | {
        scope?: T;
        actions?: T;
      };
  usage?:
    | T
    | {
        scope?: T;
        actions?: T;
      };
  'login-sessions'?:
    | T
    | {
        scope?: T;
        actions?: T;
      };
  'member-login-sessions'?:
    | T
    | {
        scope?: T;
        actions?: T;
      };
  theme?:
    | T
    | {
        actions?: T;
      };
  integrations?:
    | T
    | {
        actions?: T;
      };
  cookiePolicy?:
    | T
    | {
        actions?: T;
      };
  persona?:
    | T
    | {
        actions?: T;
      };
  prompts?:
    | T
    | {
        actions?: T;
      };
  llm?:
    | T
    | {
        actions?: T;
      };
  embedding?:
    | T
    | {
        actions?: T;
      };
  retrieval?:
    | T
    | {
        actions?: T;
      };
  memorySettings?:
    | T
    | {
        actions?: T;
      };
  limits?:
    | T
    | {
        actions?: T;
      };
  widgets?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: string;
  /**
   * Markaya özel asistan adı (frontend başlık + sekmeler)
   */
  name: string;
  /**
   * Tema ana rengi (--brand CSS değişkenine yansır)
   */
  brandColor?: string | null;
  /**
   * Site genelinde kullanılacak ana logo (SVG önerilir)
   */
  logo?: (string | null) | Media;
  /**
   * Logo açıklaması (alt text)
   */
  logoAlt: string;
  /**
   * Site faviconı (.ico, 32x32 veya 16x16)
   */
  favicon?: (string | null) | Media;
  /**
   * Modern tarayıcılar için SVG favicon
   */
  faviconSvg?: (string | null) | Media;
  /**
   * Bu içeriği oluşturan kullanıcı
   */
  createdBy?: (string | null) | User;
  /**
   * Bu içeriği güncelleyen son kullanıcı
   */
  updatedBy?: (string | null) | User;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: string;
  /**
   * Yönlendirme URI: <site>/api/assistant/auth/google/callback (yakında).
   */
  google?: {
    /**
     * İşaretliyse giriş ekranında "Google ile devam et" görünür (credential dolu olmalı).
     */
    enabled?: boolean | null;
    /**
     * Google Cloud Console → OAuth 2.0 Client ID
     */
    clientId?: string | null;
    /**
     * 🔒 Gizli
     */
    clientSecret?: string | null;
  };
  /**
   * Apple ile giriş entegrasyonu (yakında).
   */
  apple?: {
    /**
     * İşaretliyse giriş ekranında "Apple ile devam et" görünür (credential dolu olmalı).
     */
    enabled?: boolean | null;
    /**
     * Apple Developer → Identifiers → Services ID
     */
    clientId?: string | null;
    teamId?: string | null;
    keyId?: string | null;
    /**
     * 🔒 Gizli — .p8 anahtar içeriği
     */
    privateKey?: string | null;
  };
  /**
   * Bot koruması (giriş/kayıt). Site Key publictir; Secret Key gizli. (yakında)
   */
  recaptcha?: {
    enabled?: boolean | null;
    /**
     * Public (frontend'de kullanılır)
     */
    siteKey?: string | null;
    /**
     * 🔒 Gizli (sunucu doğrulaması)
     */
    secretKey?: string | null;
    /**
     * v3 skor eşiği (altı bot sayılır)
     */
    minScore?: number | null;
  };
  /**
   * Bu içeriği oluşturan kullanıcı
   */
  createdBy?: (string | null) | User;
  /**
   * Bu içeriği güncelleyen son kullanıcı
   */
  updatedBy?: (string | null) | User;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookiePolicy".
 */
export interface CookiePolicy {
  id: string;
  /**
   * Çerez politikasının aktif olup olmadığını belirler
   */
  enabled?: boolean | null;
  /**
   * Çerez politikası metni
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  acceptButton?: {
    show?: boolean | null;
    /**
     * Çerez politikasını kabul et butonunda gösterilecek metin
     */
    text?: string | null;
  };
  rejectButton?: {
    show?: boolean | null;
    /**
     * Çerez politikasını reddet butonunda gösterilecek metin
     */
    text?: string | null;
  };
  /**
   * Bu içeriği oluşturan kullanıcı
   */
  createdBy?: (string | null) | User;
  /**
   * Bu içeriği güncelleyen son kullanıcı
   */
  updatedBy?: (string | null) | User;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "persona".
 */
export interface Persona {
  id: string;
  /**
   * Sohbet ilk açıldığında gösterilen karşılama metni. Örn. "Merhaba! Size nasıl yardımcı olabilirim?"
   */
  welcomeMessage?: string | null;
  /**
   * Asistanın konuşma üslubu/kişiliği. Örn. "Resmi, kısa ve net yanıtlar ver." Sistem promptuna eklenir; güvenlik ve kaynak kurallarını değiştiremez.
   */
  persona?: string | null;
  /**
   * Boş sohbet ekranında tıklanabilir örnek sorular (en fazla 6). Örn. "İade politikanız nedir?"
   */
  suggestedQuestions?:
    | {
        question: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Bu içeriği oluşturan kullanıcı
   */
  createdBy?: (string | null) | User;
  /**
   * Bu içeriği güncelleyen son kullanıcı
   */
  updatedBy?: (string | null) | User;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompts".
 */
export interface Prompt {
  id: string;
  /**
   * Asistanın ana talimatı: yalnız kaynaklardan cevap ver, uydurma, kullanıcının dilinde yanıtla. {{persona}}, {{sources}}, {{user}} değişkenleri otomatik doldurulur.
   */
  systemPrompt?: string | null;
  /**
   * İlgili kaynak bulunamadığında gösterilen sabit yanıt. Örn. "Bu konuda elimde bilgi yok."
   */
  noContextReply?: string | null;
  /**
   * Her tur sonunda konuşma özetini güncellemek için (arka planda; bağlamı kısa tutar).
   */
  summaryPrompt?: string | null;
  /**
   * Konuşmadan kullanıcı hakkında kalıcı bilgileri çıkarır. Örn. "Kullanıcı hukukla ilgileniyor."
   */
  memoryExtractPrompt?: string | null;
  /**
   * İlk mesajdan yeni konuşmaya otomatik kısa başlık üretir.
   */
  titlePrompt?: string | null;
  /**
   * Takip sorularını (örn. "peki ya fiyatı?") önceki bağlamla bağımsız bir aramaya çevirir.
   */
  contextualizePrompt?: string | null;
  /**
   * Bu içeriği oluşturan kullanıcı
   */
  createdBy?: (string | null) | User;
  /**
   * Bu içeriği güncelleyen son kullanıcı
   */
  updatedBy?: (string | null) | User;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "llm".
 */
export interface Llm {
  id: string;
  /**
   * Yanıtı üreten LLM sağlayıcısı. Örn. OpenRouter, Anthropic (Claude), Google Gemini ya da kendi OpenAI-uyumlu sunucunuz.
   */
  provider: 'openai-compatible' | 'openrouter' | 'anthropic' | 'gemini';
  /**
   * Kullanılacak model kimliği. Örn. openai/gpt-4o-mini (OpenRouter), claude-haiku-4-5 (Anthropic), gemini-2.0-flash (Gemini).
   */
  model: string;
  /**
   * Sağlayıcının API anahtarı. 🔒 Yalnız admin görür, dışa verilmez. Örn. sk-or-v1-… (OpenRouter).
   */
  apiKey?: string | null;
  /**
   * Yalnız OpenAI-uyumlu (self-hosted/Azure/Ollama) için gerekir. Örn. http://localhost:11434/v1. Diğer sağlayıcılarda sabit (panelden değiştirilemez — güvenlik).
   */
  baseUrl?: string | null;
  /**
   * Yanıt için üst token sınırı. Örn. 1024. Yüksek = daha uzun yanıt + daha çok maliyet.
   */
  maxTokens?: number | null;
  /**
   * Yaratıcılık/çeşitlilik: 0 = tutarlı ve net, 1+ = serbest. Bilgi asistanı için 0.2–0.4 önerilir.
   */
  temperature?: number | null;
  /**
   * Bu içeriği oluşturan kullanıcı
   */
  createdBy?: (string | null) | User;
  /**
   * Bu içeriği güncelleyen son kullanıcı
   */
  updatedBy?: (string | null) | User;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "embedding".
 */
export interface Embedding {
  id: string;
  /**
   * Soruyu vektöre çeviren servis. Bilgi tabanını indekslerken kullandığınız modelle AYNI olmalı. DB kendisi vektörize ediyorsa "Yok" seçin.
   */
  provider: 'openai' | 'openai-compatible' | 'gemini' | 'none';
  /**
   * OpenAI-uyumlu embedding adresi (örn. Ollama). Örn. http://localhost:11434/v1
   */
  baseUrl?: string | null;
  /**
   * Bilgi tabanını indeksleyen embedding modeliyle AYNI olmalı. Örn. text-embedding-3-small (OpenAI), nomic-embed-text (Ollama), text-embedding-004 (Gemini).
   */
  model?: string | null;
  /**
   * Embedding servisinin API anahtarı. 🔒 Yalnız admin görür. (Ollama gibi yerel servislerde gerekmeyebilir.)
   */
  apiKey?: string | null;
  /**
   * ⚠ Vektör DB ile AYNI boyut olmalı. Örn. OpenAI 3-small: 1536, nomic-embed-text: 768. Ollama/uyumlu için BOŞ bırakın (modelin kendi boyutu kullanılır).
   */
  dimensions?: number | null;
  /**
   * Bu içeriği oluşturan kullanıcı
   */
  createdBy?: (string | null) | User;
  /**
   * Bu içeriği güncelleyen son kullanıcı
   */
  updatedBy?: (string | null) | User;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "retrieval".
 */
export interface Retrieval {
  id: string;
  /**
   * Bilgi tabanınızın tutulduğu vektör veritabanı. Örn. Qdrant, Pinecone, Weaviate.
   */
  provider: 'pinecone' | 'qdrant' | 'weaviate';
  /**
   * Vektör DB adresi. Örn. http://localhost:6333 (Qdrant) veya https://<index>-xxxx.svc.pinecone.io
   */
  url?: string | null;
  /**
   * Vektör DB erişim anahtarı (gerekiyorsa). 🔒 Yalnız admin görür. Yerel Qdrant'ta boş olabilir.
   */
  apiKey?: string | null;
  /**
   * Aranacak koleksiyon/index adı. Örn. Qdrant collection: gleam_demo · Pinecone: index adı · Weaviate: Class adı.
   */
  index?: string | null;
  /**
   * Opsiyonel bölümleme (örn. Pinecone namespace). Boş bırakılabilir.
   */
  namespace?: string | null;
  /**
   * Her soruda getirilecek en benzer pasaj sayısı. Örn. 5.
   */
  topK?: number | null;
  /**
   * Benzerlik eşiği (0–1). Bu skorun altındaki pasajlar elenir; hiçbiri geçmezse asistan "bilmiyorum" der. Örn. 0.75. (Tanılama ▸ Sorgu Testi ile ayarlayın.)
   */
  minScore?: number | null;
  /**
   * Pasaj METNİNİN saklandığı alan adı. Örn. text / content / chunk.
   */
  textKey?: string | null;
  /**
   * Bu içeriği oluşturan kullanıcı
   */
  createdBy?: (string | null) | User;
  /**
   * Bu içeriği güncelleyen son kullanıcı
   */
  updatedBy?: (string | null) | User;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memorySettings".
 */
export interface MemorySetting {
  id: string;
  /**
   * Konuşmalar ve mesajlar veritabanına kaydedilsin mi? Kapalıysa geçmiş tutulmaz (sidebar boş kalır).
   */
  persistConversations?: boolean | null;
  /**
   * Modele bağlam olarak verilecek son mesaj sayısı. Örn. 10. Yüksek = daha çok bağlam + daha çok token.
   */
  historyWindow?: number | null;
  /**
   * Kullanıcı hakkında öğrenilenleri konuşmalar arasında hatırla (ChatGPT "Memory" gibi).
   */
  crossConversation?: boolean | null;
  /**
   * Bilgi amaçlı saklama süresi (gün). Örn. 90. 0 = sınırsız. Eski veri temizliği şimdilik admin panelinden manuel yapılır.
   */
  retentionDays?: number | null;
  /**
   * Bu içeriği oluşturan kullanıcı
   */
  createdBy?: (string | null) | User;
  /**
   * Bu içeriği güncelleyen son kullanıcı
   */
  updatedBy?: (string | null) | User;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "limits".
 */
export interface Limit {
  id: string;
  /**
   * Tüm kurum için günlük toplam mesaj sınırı (maliyet sigortası). Örn. 1000. 0 = sınırsız.
   */
  dailyMessageCap?: number | null;
  /**
   * Aynı IP'nin dakikada gönderebileceği mesaj sayısı. Örn. 20. 0 = sınırsız.
   */
  perIpRateLimit?: number | null;
  /**
   * Tek bir konuşmada izin verilen maksimum mesaj. Örn. 100. 0 = sınırsız.
   */
  maxConversationMessages?: number | null;
  /**
   * Bir kullanıcının açabileceği maksimum konuşma. Örn. 50. 0 = sınırsız.
   */
  maxConversationsPerUser?: number | null;
  /**
   * Bu içeriği oluşturan kullanıcı
   */
  createdBy?: (string | null) | User;
  /**
   * Bu içeriği güncelleyen son kullanıcı
   */
  updatedBy?: (string | null) | User;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  name?: T;
  brandColor?: T;
  logo?: T;
  logoAlt?: T;
  favicon?: T;
  faviconSvg?: T;
  createdBy?: T;
  updatedBy?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  google?:
    | T
    | {
        enabled?: T;
        clientId?: T;
        clientSecret?: T;
      };
  apple?:
    | T
    | {
        enabled?: T;
        clientId?: T;
        teamId?: T;
        keyId?: T;
        privateKey?: T;
      };
  recaptcha?:
    | T
    | {
        enabled?: T;
        siteKey?: T;
        secretKey?: T;
        minScore?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookiePolicy_select".
 */
export interface CookiePolicySelect<T extends boolean = true> {
  enabled?: T;
  content?: T;
  acceptButton?:
    | T
    | {
        show?: T;
        text?: T;
      };
  rejectButton?:
    | T
    | {
        show?: T;
        text?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "persona_select".
 */
export interface PersonaSelect<T extends boolean = true> {
  welcomeMessage?: T;
  persona?: T;
  suggestedQuestions?:
    | T
    | {
        question?: T;
        id?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompts_select".
 */
export interface PromptsSelect<T extends boolean = true> {
  systemPrompt?: T;
  noContextReply?: T;
  summaryPrompt?: T;
  memoryExtractPrompt?: T;
  titlePrompt?: T;
  contextualizePrompt?: T;
  createdBy?: T;
  updatedBy?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "llm_select".
 */
export interface LlmSelect<T extends boolean = true> {
  provider?: T;
  model?: T;
  apiKey?: T;
  baseUrl?: T;
  maxTokens?: T;
  temperature?: T;
  createdBy?: T;
  updatedBy?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "embedding_select".
 */
export interface EmbeddingSelect<T extends boolean = true> {
  provider?: T;
  baseUrl?: T;
  model?: T;
  apiKey?: T;
  dimensions?: T;
  createdBy?: T;
  updatedBy?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "retrieval_select".
 */
export interface RetrievalSelect<T extends boolean = true> {
  provider?: T;
  url?: T;
  apiKey?: T;
  index?: T;
  namespace?: T;
  topK?: T;
  minScore?: T;
  textKey?: T;
  createdBy?: T;
  updatedBy?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memorySettings_select".
 */
export interface MemorySettingsSelect<T extends boolean = true> {
  persistConversations?: T;
  historyWindow?: T;
  crossConversation?: T;
  retentionDays?: T;
  createdBy?: T;
  updatedBy?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "limits_select".
 */
export interface LimitsSelect<T extends boolean = true> {
  dailyMessageCap?: T;
  perIpRateLimit?: T;
  maxConversationMessages?: T;
  maxConversationsPerUser?: T;
  createdBy?: T;
  updatedBy?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner-widget_widget".
 */
export interface BannerWidgetWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'users';
          value: string | User;
        } | null)
      | ({
          relationTo: 'cities';
          value: string | City;
        } | null)
      | ({
          relationTo: 'countries';
          value: string | Country;
        } | null)
      | ({
          relationTo: 'days';
          value: string | Day;
        } | null)
      | ({
          relationTo: 'genders';
          value: string | Gender;
        } | null)
      | ({
          relationTo: 'roles';
          value: string | Role;
        } | null);
    global?:
      | (
          | 'theme'
          | 'integrations'
          | 'cookiePolicy'
          | 'persona'
          | 'prompts'
          | 'llm'
          | 'embedding'
          | 'retrieval'
          | 'memorySettings'
          | 'limits'
        )
      | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}